-- # --- Created by Slick DDL
-- # To stop Slick DDL generation, remove this comment and start using Evolutions

# --- !Ups

create table "ROLES" ("ROLE_ID" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"ROLE" VARCHAR NOT NULL);
create unique index "role_idx" on "ROLES" ("ROLE");
create table "USERS" ("USER_ID" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"EMAIL" VARCHAR NOT NULL,"PASSWORD" VARCHAR NOT NULL,"FIRST_NAME" VARCHAR NOT NULL,"LAST_NAME" VARCHAR NOT NULL,"ROLE_ID" INTEGER);
create unique index "email_idx" on "USERS" ("EMAIL");
alter table "USERS" add constraint "ROLE_FK" foreign key("ROLE_ID") references "ROLES"("ROLE_ID") on update NO ACTION on delete NO ACTION;

insert into ROLES VALUES (1, 'ADMIN');
insert into ROLES VALUES (2, 'USER');
insert into ROLES VALUES (3, 'EXPERT');

insert into USERS VALUES (1, 'vik.kovrizhkin@gmail.com', '12345', 'Victor', 'Kovrizhkin', 1);

# --- !Downs

alter table "USERS" drop constraint "ROLE_FK";
drop table "ROLES";
drop table "USERS";